
menu:
  home: /
  archives: /archives/
  categories: /categories/ 
  tags: /tags/
  search: /search
  about: /about/
  #schedule: /schedule/
  
  #home: / || home
  #about: /about/ || user
  #tags: /tags/ || tags
  #categories: /categories/ || th
  #archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
local_search:
    enable: true
search:
  path: search.xml
  field: post
  
# html lang
language: zh-Hans

# Miscelaneous
favicon: /logo.png

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
- /js/xoxo.js

# switch
show_excerpt: true
show_date: true

#footer
index_page: https://geedchin.com
main_site: https://geedchin.com
github: https://github.com/geedchin
